/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { INFTOption, INFTOptionInterface } from "../INFTOption";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "strike_",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "buyersVaultAddress",
        type: "address",
      },
    ],
    name: "settle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class INFTOption__factory {
  static readonly abi = _abi;
  static createInterface(): INFTOptionInterface {
    return new utils.Interface(_abi) as INFTOptionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INFTOption {
    return new Contract(address, _abi, signerOrProvider) as INFTOption;
  }
}
